/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.njm.app;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import no.njm.list.LinkedList;
import no.njm.utilities.StringUtils;

public class Application {

    private static final Logger log = LoggerFactory.getLogger(Application.class);

    public static void main(String[] args) {
        LinkedList tokens = StringUtils.split(MessageUtils.getMessage());
        log.info("Joined tokens are: {}", StringUtils.join(tokens));
    }
}
